name: Fetch API Data Daily

on:
  schedule:
    - cron: '0 10 * * 1-5'  # UTC TIMEZONE - want to run every weekday at 6am EST 
  workflow_dispatch:  # Allows manual triggering


jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python get_data.py
      
      - name: Run script2
        run: python transform_data.py

      - name: Commit and push data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./data/calendar_data.jl
          git add ./data/finance.db
          git add ./logs/.
          git commit -m 'Updated jl and db files'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}